fast_obj.h
test/test.cpp
test/tiny_obj_loader.h

fast_obj wouldn't build on Windows because `fseeko` and `ftello` seem to be part of POSIX, not the standard library. I changed these to `fseek` and `ftell`, and it will now build on Windows.
Additionally, I updated the demo program for the tinyobj v1.3 api, which had breaking changes.

Removed POSIX dependency

---

fast_obj.h

In some .obj files, there's a stray 'g' followed by a newline at the
very end of the file. What happens right now is that *p++ skips past the
"terminating newline", and then proceeds to process out of bounds memory
which leads to a crash.
I'm not sure if 'g' can actually be empty per spec, so this change just
fixes the crash without resetting the group to "default" or anything
like that; 'v'/'f' shouldn't be empty but this would fix crashing when
parsing malicious/malformed .obj files as well.

Fix .obj parsing when empty 'g' is last

---

fast_obj.h

Negative indices refer to offsets of vertices (before multiplying by
stride), but array size of position/etc. is multiplied by stride.
Integer division isn't ideal for performance, however division by 3 is
lowered into integer multiplication on gcc/clang/msvc so this shouldn't
be a big concern.

Fix negative index parsing

---

fast_obj.h

For use-cases that require parsing the .obj file and outputting another
file, resolving texture paths is inconvenient since the result depends
on the path that's passed to obj_fast_read. While this can be resolved
by recomputing the relative path in user code, it seems cleaner to keep
the map names as is when parsing .mtl.
Of course, if .obj file is required for rendering, the path
concatenation is still convenient. This change makes
fastObjTexture::name contain the original data, and fastObjTexture::path
contains the resolved path that can be used to actually load the texture
if necessary.

Preserve texture name from .mtl as is

---

fast_obj.h
test/test.cpp

Instead of each group storing a separate face/index array, we now store
one large face/index array and each group stores offsets inside it.
This makes it easier to parse .obj files when group information is
unimportant since one can just skip it - group information is often
inessential as it doesn't affect rendering behavior.
This makes parsing large files slightly faster (rungholt.obj parses in
~500ms instead of ~520ms after this change).
Fixes #5.

Merge all face/index arrays together

---

fast_obj.h

Hi, very small change - it looks like the parser currently uses the wrong field when reading in the bump map texture.

Fix bump map parsing

---

fast_obj.h

When string_equal's first argument is a prefix of the second argument
but the second argument is longer, the loop goes through all characters
of the first string, compares terminating NUL with a different character
in the right hand side string, discovers that it's different and leaves
the loop - with 'a' having already been incremented.
After this the condition proceeds to read from *a which causes a buffer
overrun.
Fix this by changing the function to something that's obviously correct,
even if somewhat less efficient.

Fix buffer overflow in string_equal

---

fast_obj.h

When moving the unprocessed line to the beginning of the buffer, in rare
edge cases where the unprocessed chunk is larger than the processed
chunks (which means the lines are very long), the source & target range
will overlap. This is undefined as per C standard and triggers ubsan
errors.
Fix this by using memmove.

Fix memcpy with overlapping regions

---

fast_obj.h

Problem: on a 22gb file, it fails on "out of bound write" in the arary_size/mgrow/ngrow macros
Fix: using size_t on 64bits for arithmetic ptr alloc/index system fixes it

Adds big obj files support

---

fast_obj.h

Conversion from size_t to unsigned int is lossy.

Fix MSVC /W4 warning

---

fast_obj.h

We need it so we can include the header in a C++ project if the library itself was compiled as C.

Add extern "C" directive

---

fast_obj.h

if a name or a filepath has "spaces" in it, and "first part" of the name is similar to another it makes name matching fails
```
mtl my material
mtl my material 2
```
Then at https://github.com/thisistherk/fast_obj/blob/master/fast_obj.h#L822 previous code would always match on "my" name of material.
Texture under filepath with space in it failed too before.

Add support for name with spaces

---

fast_obj.h

**Problem:** 
I read a bare OBJ so no MTL is provided. I still want to keep the materials setup across the scene for further edit.
**Fix:** 
Instead of using a fallback material (idx 0), create a material for each 'not-defined' material while keeping the name so that the structure of the model is conserved.
**Question:** the comment `If there are no materials yet, add a dummy invalid material at index` suggests that in some cases a material can be used before it's definition. I didn't see anything preventing this to happen, and the update I'm suggesting will not give the right result in this case. 
Here is an example:
``` 
usemtl material
{geom definition}
mtllib asset.mtl
usemtl material
{geom definition}
```
(In this case, the output will have both geometries linked to the default …

Create materials even if not definition provided

---

fast_obj.h

On Windows, paths with mixed slashes weren't processed correctly as \
would be picked if it was anywhere in the path for the purpose of
determining base.
This also removes the #ifdef _WIN32 from the logic; this helps on
platforms like Emscripten where running the resulting binary that
wasn't compiled with WIN32 still needs backslash processing; paths with
backslashes on Linux should be exceedingly rare, plus we *already*
correct backslashes with forward slashes on Linux anyway...

Fix base path handling for mixed slashes

---

fast_obj.h

In some cases we need to know the length of `indices`.
Currently need to calculate the sum of the `face_vertices` elements to get this value:
```c
fastObjMesh *mesh;
// ...
unsigned int index_count = 0;
for (unsigned int f = 0; f < mesh->face_count; f++) {
index_count += mesh->face_vertices[f];
}
```
It would be convenient if we could get the value directly.

Add index_count member to fastObjMesh struct

---

fast_obj.h

When an array reached a size that would require >4GB allocation, the argument to realloc would overflow during multiplication, resulting in a very small allocation and a subsequent out of bounds access.
This change fixes that and also adjusts capacity calculation so that it doesn't overflow 32-bit range until it's basically impossible not to.
This is not perfect - in particular, on 32-bit systems there's a risk of size_t overflow that remains, however because we grow in 1.5x increments, realistically an attempt to grow a 2GB allocation to the next increment would fail before that. We can also technically overflow capacity even after the adjustment, but that requires 3+B elements which effectively means an .obj file on the scale of hundreds of gigabytes, at which point maybe a streaming …

Fix 32-bit integer overflow issues

---

fast_obj.h

I've added support for parsing colored vertex.
I've included the parsing in the parse_vertex function since in the obj, the data is on the same line as the position (v x y z r g b).
In the case there's no data, it would add 1s. I've considered adding a flag indicating whether or not the obj file has vertex colors, but then I feel like I'd have to check cases when only some vertices have colors, or if it's missing color components (am I over thinking this?)
It's my first PR so I have little knowledge of this project's standards. Feel free to let me know your thoughts and if I should keep working on this. Thanks

added support for colored vertices (issue #28)

---

fast_obj.h

Some .obj files have extra whitespace after usemtl and other statements; this may interfere with parsing, for example by adding a space to the material name which can result in inability to find it in .mtl file.
For consistency, we replace all uses of is_end_of_name with skip_name that handles this by leaving trailing whitespace alone. It will be skipped in the parsing flow when we skip the newline, which is similar to the behavior of trailing whitespace after numeric data (which parse_float/int leave alone).
Closes #37 (by providing an alternate solution)

Trim trailing whitespace for names

---

fast_obj.h

This can happen when mtllib is absent, points to a non-existing file, or material names are incorrect. In either case it helps the reader differentiate between materials that are actually specified in the file, even if their definition happens to match the default, from materials that were never loaded in the first place.

Mark materials that weren't loaded from mtllib as fallback

---

.clusterfuzzlite/Dockerfile
.clusterfuzzlite/README.md
.clusterfuzzlite/build.sh
.clusterfuzzlite/fast_obj_fuzzer.cpp
.clusterfuzzlite/project.yaml
.github/workflows/cflite_pr.yml

This adds fuzzing by way of [ClusterFuzzLite](https://google.github.io/clusterfuzzlite/), which is a GitHub action that will perform a short amount of fuzzing for new PRs.
I added a fuzzer that targets `fast_obj_read`, and currently set the timeout of CFLite to 100 seconds. CFLite will flag if the fuzzer finds any issues in the code introduced by a PR.

Add ClusterFuzzLite integration
